#!/bin/sh

ltmain="/usr/share/libtool/ltmain.sh /sw/share/libtool/libltdl/ltmain.sh"

for f in $ltmain; do
  if [ \( ! -f ltmain.sh \) -a \( -f $f \) ]; then
	ln -s $f ltmain.sh
  fi
done

rm -f config.cache
aclocal
autoconf
autoheader
automake -a
exit
